list: $/sommer/multidb/models/tenant/columns.yaml
modelClass: Sommer\MultiDB\Models\Tenant
title: Tenants
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'sommer/multidb/tenants/update/:id'
filter: config_filter.yaml